name: Academate CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-20.04  # Explicitly use ubuntu-20.04

    strategy:
      matrix:
        node-version: [20.x, 22.x]  # Updated to only include Node 20.x and 22.x

    steps:
    - uses: actions/checkout@v4  # Checkout the repository
    - name: Use Node.js ${{ matrix.node-version }}  # Set up Node.js version dynamically based on matrix
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'  # Cache yarn dependencies to speed up subsequent runs
    - run: yarn install  # Install dependencies using yarn
    - run: CI=false yarn build  # Disable ESLint in CI environment and build the app
