
name: Academate CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-20.04 

    strategy:
      matrix:
        node-version: [20.x, 22.x] 

    steps:
    - uses: actions/checkout@v4  # Checkout the repository
    - name: Use Node.js ${{ matrix.node-version }}  
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'  
    - run: npm ci  # Install dependencies using npm ci (clean installation)
    - run: npm run build  # Build the React app (no need for --if-present)
